version: 0.2

phases:
  pre_build:
    commands:
      - echo Hello...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-test:latest .
      - docker tag ecs-test:latest voiceprint/ecs-test:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push voiceprint/ecs-test:latest
